// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcRNaDl910xIha6JxPbfMtUImHz7umYIM',
    appId: '1:674269754544:web:fc3a72c45ac211b574f775',
    messagingSenderId: '674269754544',
    projectId: 'codelab-01-cee28',
    authDomain: 'codelab-01-cee28.firebaseapp.com',
    storageBucket: 'codelab-01-cee28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAr72Ewibcu5SeW5zU7WJ6DzXlEqv63HE',
    appId: '1:674269754544:android:44c6a186e957532874f775',
    messagingSenderId: '674269754544',
    projectId: 'codelab-01-cee28',
    storageBucket: 'codelab-01-cee28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdKSSt5HFzlbJdvSNYoAQGhu8Obd42vKY',
    appId: '1:674269754544:ios:3143968cc800719e74f775',
    messagingSenderId: '674269754544',
    projectId: 'codelab-01-cee28',
    storageBucket: 'codelab-01-cee28.appspot.com',
    iosBundleId: 'com.example.codelab01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdKSSt5HFzlbJdvSNYoAQGhu8Obd42vKY',
    appId: '1:674269754544:ios:3143968cc800719e74f775',
    messagingSenderId: '674269754544',
    projectId: 'codelab-01-cee28',
    storageBucket: 'codelab-01-cee28.appspot.com',
    iosBundleId: 'com.example.codelab01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcRNaDl910xIha6JxPbfMtUImHz7umYIM',
    appId: '1:674269754544:web:0044a3d0cfc932c274f775',
    messagingSenderId: '674269754544',
    projectId: 'codelab-01-cee28',
    authDomain: 'codelab-01-cee28.firebaseapp.com',
    storageBucket: 'codelab-01-cee28.appspot.com',
  );
}
